export const books = [
  {
    id: 1,
    title: "Laskar Pelangi",
    author: "Andrea Hirata",
    year: 2005,
  },
  {
    id: 2,
    title: "Bumi Manusia",
    author: "Pramoedya Ananta Toer",
    year: 1980,
  },
  {
    id: 3,
    title: "Tenggelamnya Kapal Van der Wijck",
    author: "Buya Hamka",
    year: 1938,
  },
  {
    id: 4,
    title: "Dilan: Dia adalah Dilanku Tahun 1990",
    author: "Pidi Baiq",
    year: 2014,
  },
  {
    id: 5,
    title: "Perahu Kertas",
    author: "Dee Lestari",
    year: 2009,
  },
  {
    id: 6,
    title: "Negeri 5 Menara",
    author: "Ahmad Fuadi",
    year: 2009,
  },
  {
    id: 7,
    title: "Sang Pemimpi",
    author: "Andrea Hirata",
    year: 2006,
  },
  {
    id: 8,
    title: "Ayat-Ayat Cinta",
    author: "Habiburrahman El Shirazy",
    year: 2004,
  },
  {
    id: 9,
    title: "Supernova: Ksatria, Puteri, dan Bintang Jatuh",
    author: "Dee Lestari",
    year: 2001,
  },
  {
    id: 10,
    title: "Ronggeng Dukuh Paruk",
    author: "Ahmad Tohari",
    year: 1982,
  },
  {
    id: 11,
    title: "Pulang",
    author: "Tere Liye",
    year: 2015,
  },
  {
    id: 12,
    title: "Hujan",
    author: "Tere Liye",
    year: 2016,
  },
  {
    id: 13,
    title: "Saman",
    author: "Ayu Utami",
    year: 1998,
  },
  {
    id: 14,
    title: "Gadis Kretek",
    author: "Ratih Kumala",
    year: 2012,
  },
  {
    id: 15,
    title: "Di Bawah Lindungan Ka'bah",
    author: "Buya Hamka",
    year: 1938,
  },
  {
    id: 16,
    title: "Edensor",
    author: "Andrea Hirata",
    year: 2007,
  },
  {
    id: 17,
    title: "Cantik Itu Luka",
    author: "Eka Kurniawan",
    year: 2002,
  },
  {
    id: 18,
    title: "Lelaki Harimau",
    author: "Eka Kurniawan",
    year: 2004,
  },
  {
    id: 19,
    title: "Anak Semua Bangsa",
    author: "Pramoedya Ananta Toer",
    year: 1980,
  },
  {
    id: 20,
    title: "Rindu",
    author: "Tere Liye",
    year: 2014,
  },
];
